import { GripVertical, Radio, Shuffle } from "lucide-react";
import { notFound } from "next/navigation";
import { Avatar } from "@/components/shared/avatar-stack";
import { ConfirmSubmitButton } from "@/components/shared/confirm-submit-button";
import { SessionNav } from "@/components/shared/session-nav";
import { Button } from "@/components/ui/button";
import { completeSession, createQueueMatch, startLiveMode } from "@/features/matches/actions";
import { LiveCourt } from "@/features/matches/live-court";
import { getLiveSession } from "@/features/matches/queries";
import { requireUser } from "@/features/auth/session";
import { RealtimeRefresh } from "@/features/sessions/realtime-refresh";

function playerName(player: { guestName: string | null }, profile: { name: string } | null) { return profile?.name ?? player.guestName ?? "Guest"; }

export default async function LivePage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const data = await getLiveSession((await params).id, user.id);
  if (!data) notFound();
  const isHost = data.session.hostId === user.id || data.membership?.role === "cohost";
  const waiting = data.queue.filter(({ queue }) => queue.state === "waiting");
  return <div><div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-live/10 text-live"><Radio size={21} /></span><div><p className="text-sm font-[650] text-live">{data.session.status === "live" ? "Live Mode" : "Courts"}</p><h1 className="text-2xl font-[720] tracking-[-0.02em]">{data.session.title}</h1></div></div><RealtimeRefresh sessionId={data.session.id} /></div><SessionNav id={data.session.id} active="Courts" />
    {data.session.status !== "live" ? <section className="mx-auto max-w-xl py-16 text-center"><Radio className="mx-auto text-primary" size={28} /><h2 className="mt-4 text-2xl font-bold">Start when everyone arrives</h2><p className="mx-auto mt-2 max-w-md text-pretty text-muted">Live Mode builds the waiting queue from everyone going and keeps courts, scores, and rotations together.</p>{isHost ? <form action={startLiveMode} className="mt-6"><input type="hidden" name="sessionId" value={data.session.id} /><Button>Start Live Mode</Button></form> : <p className="mt-5 text-sm font-medium text-muted">The host hasn’t started Live Mode yet.</p>}</section> : <div className="grid gap-7 pt-6 lg:grid-cols-[1fr_330px]"><section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">Active courts</h2><p className="mt-1 text-sm text-muted">Scores update for everyone here</p></div>{isHost && waiting.length >= 4 && data.activeMatches.length < data.courts.length ? <form action={createQueueMatch}><input type="hidden" name="sessionId" value={data.session.id} /><Button variant="secondary"><Shuffle size={17} />New rotation</Button></form> : null}</div>{data.activeMatches.length ? <div className="grid gap-5 xl:grid-cols-2">{data.activeMatches.map((match) => { const teamA = match.players.filter(({ matchPlayer }) => matchPlayer.team === "A").map(({ player, profile }) => playerName(player, profile)).join(" + "); const teamB = match.players.filter(({ matchPlayer }) => matchPlayer.team === "B").map(({ player, profile }) => playerName(player, profile)).join(" + "); return <LiveCourt key={match.id} sessionId={data.session.id} matchId={match.id} number={match.courtLabel} teams={[teamA, teamB]} scores={[match.teamAScore, match.teamBScore]} version={match.version} canScore={isHost} />; })}</div> : <div className="border-y border-line py-10"><h3 className="font-bold">Courts are open</h3><p className="mt-2 text-sm text-muted">{waiting.length < 4 ? `Waiting for ${4 - waiting.length} more ${4 - waiting.length === 1 ? "player" : "players"} before the first doubles match.` : "The next four players are ready for a match."}</p>{isHost && waiting.length >= 4 ? <form action={createQueueMatch} className="mt-5"><input type="hidden" name="sessionId" value={data.session.id} /><Button><Shuffle size={17} />Start first match</Button></form> : null}</div>}</section>
      <aside><div className="flex items-end justify-between"><div><h2 className="text-lg font-bold">Up next</h2><p className="mt-1 text-sm text-muted">Queue · longest waiting first</p></div></div>{waiting.length ? <ol className="mt-3 divide-y divide-line border-y border-line">{waiting.map(({ queue, player, profile }, index) => { const name = playerName(player, profile); return <li key={queue.sessionPlayerId} className="flex min-h-16 items-center gap-3 py-2"><span className="score w-5 text-center text-sm font-bold text-muted">{index + 1}</span><Avatar name={name} index={index + 1} size="sm" /><span className="flex-1 text-sm font-semibold">{name}</span>{isHost ? <GripVertical aria-label={`Move ${name}`} className="text-muted" size={19} /> : null}</li>; })}</ol> : <p className="mt-3 border-y border-line py-7 text-sm text-muted">Everyone is currently playing.</p>}<div className="mt-7 rounded-xl bg-primary-soft p-4"><p className="text-sm font-semibold">Queue rotation</p><p className="mt-1 text-sm leading-5 text-muted">The four players waiting longest form the next match. Hosts can override assignments when needed.</p></div>{data.standings.length ? <section className="mt-9"><h2 className="text-lg font-bold">Session Standings</h2><div className="mt-3 overflow-hidden border-y border-line"><table className="w-full text-sm"><thead className="text-left text-xs text-muted"><tr><th className="py-2 font-medium">Player</th><th className="py-2 text-right font-medium">W</th><th className="py-2 text-right font-medium">L</th><th className="py-2 text-right font-medium">+/−</th></tr></thead><tbody className="divide-y divide-line">{data.standings.map((row) => <tr key={row.playerId}><td className="py-3 font-medium">{row.name}</td><td className="score py-3 text-right">{row.wins}</td><td className="score py-3 text-right">{row.losses}</td><td className="score py-3 text-right">{row.differential > 0 ? "+" : ""}{row.differential}</td></tr>)}</tbody></table></div></section> : null}{isHost && !data.activeMatches.length ? <form action={completeSession} className="mt-9 border-t border-line pt-5"><input type="hidden" name="sessionId" value={data.session.id} /><ConfirmSubmitButton variant="secondary" className="w-full" confirmText="End this session? Active play will close and the game will become a shared memory.">End session</ConfirmSubmitButton><p className="mt-2 text-center text-xs text-muted">This turns the game into a permanent memory.</p></form> : null}</aside></div>}
  </div>;
}
