import type { PhilippinesVenue } from "@/features/venues/queries";

// A reviewed, deployment-local snapshot keeps the marketing page independent
// from authentication, PostgreSQL, and the map provider. The full public finder
// remains authoritative and loads current listings from the database.
export const marketingCourts: PhilippinesVenue[] = [
  {
    id: "marketing-all-day-dink",
    slug: "all-day-dink",
    name: "All Day Dink",
    address: "Casili, Consolacion, Cebu",
    latitude: 10.408,
    longitude: 123.936,
    environment: "outdoor",
    courtCount: 2,
    hours: null,
    priceRange: "Off-peak from ₱300 per hour",
    parking: null,
    amenities: [],
    paddleRental: false,
    contact: null,
    websiteUrl: null,
    socialUrl: null,
    bookingUrl: null,
    listingStatus: "verified",
    sourceUrl: null,
  },
  {
    id: "marketing-court-district",
    slug: "court-district-cebu",
    name: "Court District Cebu",
    address: "Pagsabungan, Mandaue City, Cebu",
    latitude: 10.366,
    longitude: 123.929,
    environment: "indoor",
    courtCount: 2,
    hours: null,
    priceRange: "Off-peak from ₱450 per hour",
    parking: null,
    amenities: [],
    paddleRental: true,
    contact: null,
    websiteUrl: null,
    socialUrl: null,
    bookingUrl: null,
    listingStatus: "verified",
    sourceUrl: null,
  },
  {
    id: "marketing-pickle-kiln",
    slug: "pickle-at-the-kiln",
    name: "Pickle at The Kiln",
    address: "Banilad, Mandaue City, Cebu",
    latitude: 10.354,
    longitude: 123.913,
    environment: "indoor",
    courtCount: 4,
    hours: null,
    priceRange: "Off-peak from ₱550 per hour",
    parking: null,
    amenities: [],
    paddleRental: false,
    contact: null,
    websiteUrl: null,
    socialUrl: null,
    bookingUrl: null,
    listingStatus: "verified",
    sourceUrl: null,
  },
  {
    id: "marketing-dula",
    slug: "dula-pickleball-courts-cebu",
    name: "DULA Pickleball Courts Cebu",
    address: "F.E. Zuellig Avenue, Mandaue City, Cebu",
    latitude: 10.337,
    longitude: 123.946,
    environment: "indoor",
    courtCount: 8,
    hours: null,
    priceRange: "Rates vary by time",
    parking: null,
    amenities: [],
    paddleRental: true,
    contact: null,
    websiteUrl: null,
    socialUrl: null,
    bookingUrl: null,
    listingStatus: "verified",
    sourceUrl: null,
  },
  {
    id: "marketing-hq",
    slug: "hq-pickleball-cebu",
    name: "HQ Pickleball Cebu",
    address: "Cebu Business Park, Cebu City",
    latitude: 10.318,
    longitude: 123.906,
    environment: "outdoor",
    courtCount: 3,
    hours: null,
    priceRange: "From ₱500 per hour",
    parking: null,
    amenities: [],
    paddleRental: true,
    contact: null,
    websiteUrl: null,
    socialUrl: null,
    bookingUrl: null,
    listingStatus: "verified",
    sourceUrl: null,
  },
  {
    id: "marketing-mactan",
    slug: "mactan-pickleball-club",
    name: "Mactan Pickleball Club",
    address: "Mactan, Lapu-Lapu City, Cebu",
    latitude: 10.303,
    longitude: 123.972,
    environment: "outdoor",
    courtCount: 3,
    hours: null,
    priceRange: "Weekdays from ₱500 per hour",
    parking: null,
    amenities: [],
    paddleRental: false,
    contact: null,
    websiteUrl: null,
    socialUrl: null,
    bookingUrl: null,
    listingStatus: "verified",
    sourceUrl: null,
  },
];
