import type { CourtListing } from "@/features/venues/directory";

// A reviewed, deployment-local snapshot keeps the marketing page independent
// from authentication, PostgreSQL, and the map provider. The full public finder
// remains authoritative and loads current listings from the database.
const marketingSnapshot = [
  {
    id: "marketing-all-day-dink",
    slug: "all-day-dink",
    name: "All Day Dink",
    address: "Casili, Consolacion, Cebu",
    latitude: 10.408,
    longitude: 123.936,
    environment: "outdoor",
    courtCount: 2,
    priceStatus: "paid",
    priceAmountCents: 30000,
    priceLabel: "Off-peak from ₱300 per hour",
    paddleRental: false,
  },
  {
    id: "marketing-court-district",
    slug: "court-district-cebu",
    name: "Court District Cebu",
    address: "Pagsabungan, Mandaue City, Cebu",
    latitude: 10.366,
    longitude: 123.929,
    environment: "indoor",
    courtCount: 2,
    priceStatus: "paid",
    priceAmountCents: 45000,
    priceLabel: "Off-peak from ₱450 per hour",
    paddleRental: true,
  },
  {
    id: "marketing-pickle-kiln",
    slug: "pickle-at-the-kiln",
    name: "Pickle at The Kiln",
    address: "Banilad, Mandaue City, Cebu",
    latitude: 10.354,
    longitude: 123.913,
    environment: "indoor",
    courtCount: 4,
    priceStatus: "paid",
    priceAmountCents: 55000,
    priceLabel: "Off-peak from ₱550 per hour",
    paddleRental: false,
  },
  {
    id: "marketing-dula",
    slug: "dula-pickleball-courts-cebu",
    name: "DULA Pickleball Courts Cebu",
    address: "F.E. Zuellig Avenue, Mandaue City, Cebu",
    latitude: 10.337,
    longitude: 123.946,
    environment: "indoor",
    courtCount: 8,
    priceStatus: "unknown",
    priceAmountCents: null,
    priceLabel: "Rates vary by time",
    paddleRental: true,
  },
  {
    id: "marketing-hq",
    slug: "hq-pickleball-cebu",
    name: "HQ Pickleball Cebu",
    address: "Cebu Business Park, Cebu City",
    latitude: 10.318,
    longitude: 123.906,
    environment: "outdoor",
    courtCount: 3,
    priceStatus: "paid",
    priceAmountCents: 50000,
    priceLabel: "From ₱500 per hour",
    paddleRental: true,
  },
  {
    id: "marketing-mactan",
    slug: "mactan-pickleball-club",
    name: "Mactan Pickleball Club",
    address: "Mactan, Lapu-Lapu City, Cebu",
    latitude: 10.303,
    longitude: 123.972,
    environment: "outdoor",
    courtCount: 3,
    priceStatus: "paid",
    priceAmountCents: 50000,
    priceLabel: "Weekdays from ₱500 per hour",
    paddleRental: false,
  },
] as const;

export const marketingCourts: CourtListing[] = marketingSnapshot.map((court) => ({
  ...court,
  accessType: "commercial",
  reservationPolicy: "reservation_required",
  operationalStatus: "operating",
  operatingHours: [],
  priceMaxCents: null,
  priceUnit: court.priceStatus === "paid" ? "hour" : null,
  parkingStatus: null,
  parkingLabel: null,
  amenities: [],
  contact: null,
  websiteUrl: null,
  socialUrl: null,
  bookingUrl: null,
  listingStatus: "verified",
  sourceUrl: null,
  verifiedAt: null,
  lastSeenAt: null,
}));
