import Link from "next/link";
import { ArrowSquareOut, CaretRight, CurrencyCircleDollar, PencilSimple, ShieldCheck } from "@phosphor-icons/react/dist/ssr";
import { notFound } from "next/navigation";
import { SessionNav } from "@/components/shared/session-nav";
import { DeleteSessionControl } from "@/features/sessions/delete-session-control";
import { requireUser } from "@/features/auth/session";
import { sessionAccentStyle } from "@/features/sessions/accent";
import { getSessionForParticipant } from "@/features/sessions/queries";

export default async function MorePage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser(); const sessionId = (await params).id;
  const data = await getSessionForParticipant(sessionId, user.id); if (!data) notFound();
  const isHost = data.session.hostId === user.id || data.membership?.role === "cohost";
  return <div style={sessionAccentStyle(data.session.accentColor)}><div className="mb-5"><p className="text-sm font-semibold text-primary">{data.session.title}</p><h1 className="mt-1 app-title">More</h1></div><SessionNav id={sessionId} active="More" /><div className="mx-auto max-w-2xl py-7"><section className="divide-y divide-line border-y border-line">{isHost ? <Link href={`/games/${sessionId}/settings`} className="flex min-h-16 items-center gap-3 py-3"><PencilSimple aria-hidden className="text-primary" size={18} /><div className="flex-1"><p className="font-semibold">Game settings</p><p className="mt-1 text-sm text-muted">Edit the plan, venue, player limit, courts, and booking.</p></div><CaretRight aria-hidden className="text-muted" size={17} /></Link> : null}<Link href={`/games/${sessionId}/payments`} className="flex min-h-16 items-center gap-3 py-3"><CurrencyCircleDollar aria-hidden className="text-primary" size={18} /><div className="flex-1"><p className="font-semibold">Payments</p><p className="mt-1 text-sm text-muted">View your share, payment details, and proof status.</p></div><CaretRight aria-hidden className="text-muted" size={17} /></Link><Link href={`/s/${data.session.slug}`} className="flex min-h-16 items-center justify-between py-3"><div><p className="font-semibold">Public game page</p><p className="mt-1 text-sm text-muted">Preview the link your friends receive.</p></div><ArrowSquareOut className="text-muted" size={17} /></Link><div className="flex min-h-16 items-center gap-3 py-3"><ShieldCheck className="text-primary" /><div><p className="font-semibold">{isHost ? "You manage this game" : "Participant access"}</p><p className="mt-1 text-sm text-muted">{isHost ? "Roster, courts, scoring, and payment controls are available to you." : "Only hosts can change shared session details."}</p></div></div></section><section className="mt-9"><h2 className="font-bold">Session status</h2><dl className="mt-3 divide-y divide-line border-y border-line text-sm"><div className="flex justify-between py-4"><dt className="text-muted">Visibility</dt><dd className="font-medium capitalize">{data.session.visibility}</dd></div><div className="flex justify-between py-4"><dt className="text-muted">Rotation</dt><dd className="font-medium capitalize">{data.session.rotationMode.replaceAll("_", " ")}</dd></div><div className="flex justify-between py-4"><dt className="text-muted">Roster</dt><dd className="font-medium">{data.session.rosterLocked ? "Locked" : "Open"}</dd></div></dl></section>{data.session.hostId === user.id ? <section className="mt-10" aria-labelledby="danger-zone-title"><h2 id="danger-zone-title" className="text-sm font-semibold text-danger">Danger zone</h2><div className="mt-2 border-y border-line"><DeleteSessionControl sessionId={sessionId} title={data.session.title} /></div></section> : null}</div></div>;
}
