import { eq } from "drizzle-orm";
import Image from "next/image";
import { CheckCircle, CircleDashed, CurrencyCircleDollar, Image as ImageIcon } from "@phosphor-icons/react/dist/ssr";
import { notFound } from "next/navigation";
import { SessionNav } from "@/components/shared/session-nav";
import { ImageFileField } from "@/components/ui/image-file-field";
import { SelectField } from "@/components/ui/select-field";
import { SubmitButton } from "@/components/ui/submit-button";
import { db } from "@/db/client";
import { expenses, paymentAccounts, playerPayments, profiles, sessionPlayers } from "@/db/schema";
import { requireUser } from "@/features/auth/session";
import { confirmPayment, createExpense, requestNewPaymentProof, togglePaymentExcluded, updatePlayerPaymentAmount } from "@/features/payments/actions";
import { PaymentProofForm } from "@/features/payments/payment-proof-form";
import { sessionAccentStyle } from "@/features/sessions/accent";
import { peso } from "@/features/sessions/format";
import { getSessionForParticipant } from "@/features/sessions/queries";
import { ShareButton } from "@/features/sessions/share-button";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const input = "mt-1.5 h-11 w-full rounded-lg border border-line bg-surface px-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/15";

function paymentLabel(status: string, requested: boolean) {
  if (status === "confirmed") return "Paid";
  if (status === "sent") return "Proof sent";
  if (status === "excluded") return "Not included";
  return requested ? "New proof requested" : "Unpaid";
}

export default async function PaymentsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const sessionId = (await params).id;
  const data = await getSessionForParticipant(sessionId, user.id);
  if (!data) notFound();
  const isHost = data.session.hostId === user.id || data.membership?.role === "cohost";
  const hostName = data.roster.find(({ player }) => player.role === "host")?.profile?.name ?? "The host";
  const sessionExpenses = await db.select({ expense: expenses, account: paymentAccounts }).from(expenses).leftJoin(paymentAccounts, eq(expenses.paymentAccountId, paymentAccounts.id)).where(eq(expenses.sessionId, sessionId));
  const rows = await db.select({ payment: playerPayments, player: sessionPlayers, profile: profiles, expense: expenses }).from(playerPayments).innerJoin(sessionPlayers, eq(playerPayments.sessionPlayerId, sessionPlayers.id)).leftJoin(profiles, eq(sessionPlayers.userId, profiles.userId)).innerJoin(expenses, eq(playerPayments.expenseId, expenses.id)).where(eq(expenses.sessionId, sessionId));
  const supabase = createSupabaseAdminClient();
  const collectibleRows = rows.filter(({ player }) => player.userId !== data.session.hostId);
  const visibleRows = isHost ? collectibleRows : collectibleRows.filter(({ player }) => player.userId === user.id);
  const visiblePayments = await Promise.all(visibleRows.map(async (row) => ({ ...row, proofUrl: row.payment.proofStoragePath ? (await supabase.storage.from("payment-proofs").createSignedUrl(row.payment.proofStoragePath, 3600)).data?.signedUrl ?? null : null })));
  const qrUrls = new Map<string, string>();
  const receiptUrls = new Map<string, string>();
  await Promise.all(sessionExpenses.flatMap(({ expense, account }) => [
    account?.qrStoragePath ? supabase.storage.from("payment-qrs").createSignedUrl(account.qrStoragePath, 3600).then(({ data: signed }) => { if (signed?.signedUrl) qrUrls.set(account.id, signed.signedUrl); }) : Promise.resolve(),
    expense.receiptStoragePath ? supabase.storage.from("booking-screenshots").createSignedUrl(expense.receiptStoragePath, 3600).then(({ data: signed }) => { if (signed?.signedUrl) receiptUrls.set(expense.id, signed.signedUrl); }) : Promise.resolve(),
  ]));

  return <div style={sessionAccentStyle(data.session.accentColor)}><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-primary">{data.session.title}</p><h1 className="mt-1 app-title">{isHost ? "Payments" : "Your payment"}</h1><p className="mt-2 max-w-xl text-sm text-muted">{isHost ? "Collect player shares and review proof." : "Repay the host, then upload one screenshot."} Relay tracks status only.</p></div>{isHost ? <ShareButton url={`/s/${data.session.slug}`} title={data.session.title} /> : null}</div><SessionNav id={sessionId} active="Payments" />
    {sessionExpenses.length ? <div className="grid gap-8 pt-7 lg:grid-cols-[1fr_340px]"><section className="space-y-10">{sessionExpenses.map(({ expense }) => { const expensePayments = visiblePayments.filter((row) => row.expense.id === expense.id); const confirmed = expensePayments.filter((row) => row.payment.status === "confirmed").length; return <article key={expense.id}><div className="flex items-end justify-between border-b border-line pb-5"><div><p className="text-sm capitalize text-muted">{expense.kind.replaceAll("_", " ")}</p><p className="score mt-1 text-3xl font-bold">{peso(expense.totalCents)} <span className="text-base font-medium text-muted">total</span></p></div><p className="text-sm text-muted">{confirmed} of {expensePayments.length} paid</p></div><div className="flex min-h-16 items-center gap-3 border-b border-line py-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-primary-soft text-sm font-bold text-primary">{hostName.slice(0, 1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="font-[650]">{hostName}</p><p className="mt-0.5 text-xs text-muted">Host · paid the full amount upfront</p></div><span className="text-sm font-semibold text-success">Paid</span></div><ul className="divide-y divide-line">{expensePayments.map(({ payment, player, profile, proofUrl }) => { const own = player.userId === user.id; const name = profile?.name ?? player.guestName ?? "Guest"; const requested = Boolean(payment.reviewNote); return <li key={payment.id} className="py-4"><div className="flex flex-wrap items-center gap-3"><span className="min-w-32 flex-1 font-medium">{name}</span><span className="score text-sm font-semibold">{peso(payment.amountCents)}</span><span className={`inline-flex items-center gap-1.5 text-sm font-medium ${payment.status === "confirmed" ? "text-success" : requested ? "text-warning" : "text-muted"}`}>{payment.status === "confirmed" ? <CheckCircle aria-hidden size={16} /> : <CircleDashed aria-hidden size={16} />}{paymentLabel(payment.status, requested)}</span></div>
              {isHost && payment.status !== "sent" && payment.status !== "confirmed" ? <details className="mt-2"><summary className="pressable inline-flex min-h-9 cursor-pointer items-center rounded-lg px-3 text-[13px] font-[600] leading-none text-muted hover:bg-surface-strong hover:text-ink">Adjust player share</summary><div className="mt-2 flex flex-wrap items-center gap-2"><form action={updatePlayerPaymentAmount} className="flex items-center gap-2"><input type="hidden" name="paymentId" value={payment.id} /><label className="sr-only" htmlFor={`amount-${payment.id}`}>Amount for {name}</label><div className="relative"><span className="absolute left-2.5 top-2 text-xs text-muted">₱</span><input id={`amount-${payment.id}`} name="amount" type="number" min="0" step="0.01" defaultValue={payment.amountCents / 100} className="score h-9 w-28 rounded-md border border-line bg-surface pl-6 pr-2 text-sm" /></div><SubmitButton pendingLabel="Saving…" variant="secondary" className="min-h-9">Save</SubmitButton></form><form action={togglePaymentExcluded}><input type="hidden" name="paymentId" value={payment.id} /><SubmitButton pendingLabel="Updating…" variant="quiet" className="min-h-9">{payment.status === "excluded" ? "Include" : "Exclude"}</SubmitButton></form></div></details> : null}
              {own && payment.status === "unpaid" ? <PaymentProofForm paymentId={payment.id} reviewNote={payment.reviewNote} /> : null}
              {payment.status === "sent" ? <div className="mt-3 flex flex-wrap items-start gap-3 rounded-lg bg-surface-strong p-3">{proofUrl ? <a href={proofUrl} target="_blank" rel="noreferrer" className="overflow-hidden rounded-lg"><Image src={proofUrl} alt={`Payment proof from ${name}`} width={88} height={88} className="h-[88px] w-[88px] object-cover" /></a> : <span className="grid h-[88px] w-[88px] place-items-center rounded-lg bg-surface text-muted"><ImageIcon aria-hidden /></span>}<div className="min-w-48 flex-1"><p className="text-sm font-[650]">Waiting for host review</p><p className="mt-1 text-xs leading-5 text-muted">Submitted proof does not mark payment paid until the host confirms it.</p>{isHost ? <div className="mt-3 flex flex-wrap items-start gap-2"><form action={confirmPayment}><input type="hidden" name="paymentId" value={payment.id} /><SubmitButton pendingLabel="Confirming…">Confirm paid</SubmitButton></form><details><summary className="pressable inline-flex min-h-9 cursor-pointer items-center rounded-lg border border-line bg-surface px-3 text-[13px] font-[600] leading-none text-ink hover:bg-surface-strong">Request new proof</summary><form action={requestNewPaymentProof} className="mt-2 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="paymentId" value={payment.id} /><label className="sr-only" htmlFor={`note-${payment.id}`}>Reason for requesting new proof</label><input id={`note-${payment.id}`} name="note" required minLength={2} maxLength={240} placeholder="What needs to be clearer?" className="h-11 min-w-0 flex-1 rounded-lg border border-line bg-surface px-3 text-sm" /><SubmitButton pendingLabel="Sending request…" variant="secondary">Send request</SubmitButton></form></details></div> : null}</div></div> : null}
            </li>; })}</ul></article>; })}</section><aside className="self-start rounded-lg border border-line bg-surface p-5 lg:sticky lg:top-6"><CurrencyCircleDollar className="text-primary" size={20} /><h2 className="mt-4 font-bold">Repay the host</h2><p className="mt-2 text-sm font-medium">{sessionExpenses[0].account?.method}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-5 text-muted">{sessionExpenses[0].account?.details}</p>{sessionExpenses[0].account && qrUrls.get(sessionExpenses[0].account.id) ? <Image src={qrUrls.get(sessionExpenses[0].account.id)!} alt={`${sessionExpenses[0].account.method} payment QR`} width={240} height={240} className="mt-4 aspect-square w-full rounded-lg border border-line object-contain" /> : null}{receiptUrls.get(sessionExpenses[0].expense.id) ? <a href={receiptUrls.get(sessionExpenses[0].expense.id)!} target="_blank" rel="noreferrer" className="mt-5 flex items-center gap-3 border-t border-line pt-4"><Image src={receiptUrls.get(sessionExpenses[0].expense.id)!} alt="Receipt uploaded by the host" width={48} height={48} className="h-12 w-12 rounded-md border border-line object-cover" /><span><strong className="block text-sm">View host receipt</strong><span className="mt-0.5 block text-xs text-muted">Proof the expense was paid upfront</span></span></a> : null}<p className="mt-5 border-t border-line pt-4 text-xs leading-5 text-muted">Send your share to the host, then upload one screenshot. The host reviews it before Relay marks you paid.</p></aside></div>
      : isHost ? <section className="mx-auto max-w-xl py-10"><CurrencyCircleDollar className="text-primary" size={20} /><h2 className="mt-4 text-xl font-bold">Collect player shares</h2><p className="mt-2 text-sm leading-6 text-muted">You paid the expense upfront. Relay divides it among the other players, then helps you review repayments.</p><form action={createExpense} className="mt-7 space-y-4"><input type="hidden" name="sessionId" value={sessionId} /><div><label className="text-sm font-semibold" htmlFor="label">Expense</label><input className={input} id="label" name="label" defaultValue="Court" required /></div><div><label className="text-sm font-semibold" htmlFor="total">Total amount</label><input className={`${input} score`} id="total" name="total" type="number" min="1" step="0.01" required inputMode="decimal" autoComplete="off" placeholder="2400" /></div><SelectField id="method" name="method" label="Payment method" defaultValue="GCash" options={[{ value: "GCash", label: "GCash" }, { value: "Maya", label: "Maya" }, { value: "Bank transfer", label: "Bank transfer" }, { value: "Cash", label: "Cash" }, { value: "Custom", label: "Custom" }]} /><div><label className="text-sm font-semibold" htmlFor="details">Payment details</label><textarea className="mt-1.5 min-h-24 w-full rounded-lg border border-line bg-surface p-3.5" id="details" name="details" required autoComplete="off" placeholder="Account name and number…" /></div><ImageFileField id="payment-qr" name="qr" label="Payment QR (optional)" hint="Players can scan this to repay you." buttonLabel="Choose QR image" /><ImageFileField id="expense-receipt" name="receipt" label="Receipt (optional)" hint="Show players that you already paid the venue or expense." buttonLabel="Choose receipt" /><SubmitButton pendingLabel="Creating split…" className="w-full">Create collection</SubmitButton></form></section>
      : <section className="mx-auto max-w-xl py-14"><CircleDashed className="text-primary" /><h2 className="mt-4 text-xl font-bold">Payment details aren’t set up</h2><p className="mt-2 text-pretty text-muted">{data.session.estimatedCostCents ? `The current estimate is ${peso(data.session.estimatedCostCents)} per player. The host hasn’t requested payment yet.` : "The host hasn’t added an expense or payment method."}</p></section>}
  </div>;
}
