import { eq } from "drizzle-orm";
import Image from "next/image";
import { CheckCircle, CircleDashed, CurrencyCircleDollar, Image as ImageIcon } from "@phosphor-icons/react/dist/ssr";
import { notFound } from "next/navigation";
import { SessionNav } from "@/components/shared/session-nav";
import { Button } from "@/components/ui/button";
import { db } from "@/db/client";
import { expenses, paymentAccounts, playerPayments, profiles, sessionPlayers } from "@/db/schema";
import { requireUser } from "@/features/auth/session";
import { confirmPayment, createExpense, requestNewPaymentProof } from "@/features/payments/actions";
import { PaymentProofForm } from "@/features/payments/payment-proof-form";
import { peso } from "@/features/sessions/format";
import { getSessionForUser } from "@/features/sessions/queries";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const input = "mt-1.5 h-11 w-full rounded-lg border border-line bg-surface px-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/15";

function paymentLabel(status: string, requested: boolean) {
  if (status === "confirmed") return "Paid";
  if (status === "sent") return "Proof sent";
  return requested ? "New proof requested" : "Unpaid";
}

export default async function PaymentsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const sessionId = (await params).id;
  const data = await getSessionForUser(sessionId, user.id);
  if (!data) notFound();
  const isHost = data.session.hostId === user.id;
  const sessionExpenses = await db.select({ expense: expenses, account: paymentAccounts }).from(expenses).leftJoin(paymentAccounts, eq(expenses.paymentAccountId, paymentAccounts.id)).where(eq(expenses.sessionId, sessionId));
  const rows = await db.select({ payment: playerPayments, player: sessionPlayers, profile: profiles, expense: expenses }).from(playerPayments).innerJoin(sessionPlayers, eq(playerPayments.sessionPlayerId, sessionPlayers.id)).leftJoin(profiles, eq(sessionPlayers.userId, profiles.userId)).innerJoin(expenses, eq(playerPayments.expenseId, expenses.id)).where(eq(expenses.sessionId, sessionId));
  const supabase = createSupabaseAdminClient();
  const payments = await Promise.all(rows.map(async (row) => ({ ...row, proofUrl: row.payment.proofStoragePath ? (await supabase.storage.from("payment-proofs").createSignedUrl(row.payment.proofStoragePath, 3600)).data?.signedUrl ?? null : null })));

  return <div><div className="mb-5"><p className="text-sm font-semibold text-primary">{data.session.title}</p><h1 className="mt-1 app-title">Payments</h1><p className="mt-2 max-w-xl text-sm text-muted">Split shared costs and review proof. Relay records status only—it never moves money.</p></div><SessionNav id={sessionId} active="More" />
    {sessionExpenses.length ? <div className="grid gap-8 pt-7 lg:grid-cols-[1fr_340px]"><section className="space-y-10">{sessionExpenses.map(({ expense }) => { const expensePayments = payments.filter((row) => row.expense.id === expense.id); const confirmed = expensePayments.filter((row) => row.payment.status === "confirmed").length; return <article key={expense.id}><div className="flex items-end justify-between border-b border-line pb-5"><div><p className="text-sm capitalize text-muted">{expense.kind.replaceAll("_", " ")}</p><p className="score mt-1 text-3xl font-bold">{peso(expense.totalCents)} <span className="text-base font-medium text-muted">total</span></p></div><p className="text-sm text-muted">{confirmed} of {expensePayments.length} paid</p></div><ul className="divide-y divide-line">{expensePayments.map(({ payment, player, profile, proofUrl }) => { const own = player.userId === user.id; const name = profile?.name ?? player.guestName ?? "Guest"; const requested = Boolean(payment.reviewNote); return <li key={payment.id} className="py-4"><div className="flex flex-wrap items-center gap-3"><span className="min-w-32 flex-1 font-medium">{name}</span><span className="score text-sm font-semibold">{peso(payment.amountCents)}</span><span className={`inline-flex items-center gap-1.5 text-sm font-medium ${payment.status === "confirmed" ? "text-success" : requested ? "text-warning" : "text-muted"}`}>{payment.status === "confirmed" ? <CheckCircle aria-hidden size={16} /> : <CircleDashed aria-hidden size={16} />}{paymentLabel(payment.status, requested)}</span></div>
              {own && payment.status === "unpaid" ? <PaymentProofForm paymentId={payment.id} reviewNote={payment.reviewNote} /> : null}
              {payment.status === "sent" ? <div className="mt-3 flex flex-wrap items-start gap-3 rounded-lg bg-surface-strong p-3">{proofUrl ? <a href={proofUrl} target="_blank" rel="noreferrer" className="overflow-hidden rounded-lg"><Image src={proofUrl} alt={`Payment proof from ${name}`} width={88} height={88} className="h-[88px] w-[88px] object-cover" /></a> : <span className="grid h-[88px] w-[88px] place-items-center rounded-lg bg-surface text-muted"><ImageIcon aria-hidden /></span>}<div className="min-w-48 flex-1"><p className="text-sm font-[650]">Waiting for host review</p><p className="mt-1 text-xs leading-5 text-muted">Submitted proof does not mark payment paid until the host confirms it.</p>{isHost ? <div className="mt-3 flex flex-wrap items-start gap-2"><form action={confirmPayment}><input type="hidden" name="paymentId" value={payment.id} /><Button>Confirm paid</Button></form><details><summary className="inline-flex min-h-11 cursor-pointer items-center rounded-lg px-3 text-sm font-[650] text-muted hover:bg-surface">Request new proof</summary><form action={requestNewPaymentProof} className="mt-2 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="paymentId" value={payment.id} /><label className="sr-only" htmlFor={`note-${payment.id}`}>Reason for requesting new proof</label><input id={`note-${payment.id}`} name="note" required minLength={2} maxLength={240} placeholder="What needs to be clearer?" className="h-11 min-w-0 flex-1 rounded-lg border border-line bg-surface px-3 text-sm" /><Button variant="secondary">Send request</Button></form></details></div> : null}</div></div> : null}
            </li>; })}</ul></article>; })}</section><aside className="self-start rounded-lg border border-line bg-surface p-5 lg:sticky lg:top-6"><CurrencyCircleDollar className="text-primary" size={20} /><h2 className="mt-4 font-bold">How to pay</h2><p className="mt-2 text-sm font-medium">{sessionExpenses[0].account?.method}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-5 text-muted">{sessionExpenses[0].account?.details}</p><p className="mt-5 border-t border-line pt-4 text-xs leading-5 text-muted">Pay in the listed app, then upload one screenshot. The host reviews it before Relay marks you paid.</p></aside></div>
      : isHost ? <section className="mx-auto max-w-xl py-10"><CurrencyCircleDollar className="text-primary" size={20} /><h2 className="mt-4 text-xl font-bold">Request payment</h2><p className="mt-2 text-sm text-muted">Relay divides the total among everyone currently going. Payments still happen through your chosen method.</p><form action={createExpense} className="mt-7 space-y-4"><input type="hidden" name="sessionId" value={sessionId} /><div><label className="text-sm font-semibold" htmlFor="label">Expense</label><input className={input} id="label" name="label" defaultValue="Court" required /></div><div><label className="text-sm font-semibold" htmlFor="total">Total amount</label><input className={`${input} score`} id="total" name="total" type="number" min="1" step="0.01" required inputMode="decimal" autoComplete="off" placeholder="2400" /></div><div><label className="text-sm font-semibold" htmlFor="method">Payment method</label><select className={input} id="method" name="method" defaultValue="GCash"><option>GCash</option><option>Maya</option><option>Bank transfer</option><option>Cash</option><option>Custom</option></select></div><div><label className="text-sm font-semibold" htmlFor="details">Payment details</label><textarea className="mt-1.5 min-h-24 w-full rounded-lg border border-line bg-surface p-3.5" id="details" name="details" required autoComplete="off" placeholder="Account name and number…" /></div><Button className="w-full">Create payment split</Button></form></section>
      : <section className="mx-auto max-w-xl py-14"><CircleDashed className="text-primary" /><h2 className="mt-4 text-xl font-bold">Payment details aren’t set up</h2><p className="mt-2 text-pretty text-muted">{data.session.estimatedCostCents ? `The current estimate is ${peso(data.session.estimatedCostCents)} per player. The host hasn’t requested payment yet.` : "The host hasn’t added an expense or payment method."}</p></section>}
  </div>;
}
