#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".env.local"

PROJECT_NAME="relay-pickleball"
VERCEL_PROJECT_NAME="relay-pickleball"
VERCEL_SCOPE="van-aj-vanguardias-projects"
REGION="ap-southeast-1"
ORG_ID=""

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 is required but is not installed."
    exit 1
  fi
}

project_ref_for_name() {
  supabase projects list --output json | node -e '
    let body = "";
    process.stdin.on("data", chunk => body += chunk);
    process.stdin.on("end", () => {
      const project = JSON.parse(body).find(item => item.name === process.argv[1]);
      if (project) process.stdout.write(project.ref ?? project.id);
    });
  ' "$1"
}

project_status_for_ref() {
  supabase projects list --output json | node -e '
    let body = "";
    process.stdin.on("data", chunk => body += chunk);
    process.stdin.on("end", () => {
      const project = JSON.parse(body).find(item => (item.ref ?? item.id) === process.argv[1]);
      if (project) process.stdout.write(project.status ?? "");
    });
  ' "$1"
}

first_org_id() {
  supabase orgs list --output json | node -e '
    let body = "";
    process.stdin.on("data", chunk => body += chunk);
    process.stdin.on("end", () => {
      const organizations = JSON.parse(body);
      if (organizations.length === 1) process.stdout.write(organizations[0].id);
    });
  '
}

set_vercel_env() {
  local key="$1" value="$2" environment
  for environment in production preview; do
    printf '%s' "$value" | vercel env add "$key" "$environment" --force --yes >/dev/null
    printf '  %s✓ set%s Vercel %s for %s\n' "$GREEN" "$RESET" "$key" "$environment"
  done
}

banner "Relay integrations setup"

stage "Supabase — create the project"
require_command node
require_command supabase
require_command vercel
require_command corepack
say "This creates Relay in Singapore (${REGION}), the closest Supabase region for Philippine users."
step "Project name: ${PROJECT_NAME}"
ORG_ID=$(first_org_id || true)
if [[ -z "$ORG_ID" ]]; then
  step "Your account has multiple organizations. Run 'supabase orgs list' in another terminal."
  ask ORG_ID "Paste the organization ID to use:"
fi
step "Supabase organization: ${ORG_ID}"
PROJECT_REF=$(project_ref_for_name "$PROJECT_NAME" || true)
if [[ -z "$PROJECT_REF" ]]; then
  ask_secret SUPABASE_DB_PASSWORD "Choose a strong database password (16+ characters):"
  if [[ ${#SUPABASE_DB_PASSWORD} -lt 16 ]]; then
    warn "Use at least 16 characters for the database password."
    exit 1
  fi
  if confirm "Create the Supabase project now?"; then
    supabase projects create "$PROJECT_NAME" \
      --org-id "$ORG_ID" \
      --db-password "$SUPABASE_DB_PASSWORD" \
      --region "$REGION" \
      --yes
  else
    warn "Project creation declined. No cloud resources were changed."
    exit 1
  fi

  say "Waiting for Supabase to assign the project reference..."
  for _ in {1..40}; do
    PROJECT_REF=$(project_ref_for_name "$PROJECT_NAME" || true)
    [[ -n "$PROJECT_REF" ]] && break
    sleep 15
  done
  if [[ -z "$PROJECT_REF" ]]; then
    warn "The project is still provisioning. Re-run this wizard in a few minutes."
    exit 1
  fi
else
  say "Found the existing ${PROJECT_NAME} project; creation is skipped."
fi
say "Waiting for the database to become healthy..."
for _ in {1..40}; do
  PROJECT_STATUS=$(project_status_for_ref "$PROJECT_REF" || true)
  [[ "$PROJECT_STATUS" == "ACTIVE_HEALTHY" ]] && break
  sleep 15
done
if [[ "${PROJECT_STATUS:-}" != "ACTIVE_HEALTHY" ]]; then
  warn "Project status is ${PROJECT_STATUS:-unknown}. Re-run after Supabase finishes provisioning."
  exit 1
fi
write_env SUPABASE_PROJECT_REF "$PROJECT_REF"
write_env SUPABASE_REGION "$REGION"
note "Project reference: $PROJECT_REF"

stage "Supabase — API and database credentials"
say "The app uses modern publishable/secret keys and the transaction pooler for Vercel IPv4 compatibility."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/api-keys"
step "Copy the Publishable key (starts with sb_publishable_)."
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Reveal and copy the Secret key (starts with sb_secret_)."
ask_secret SUPABASE_SECRET_KEY "Paste the secret key:"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}"
step "Click Connect, choose Transaction pooler, and copy the URI. Replace [YOUR-PASSWORD] before pasting."
ask_secret DATABASE_URL "Paste the complete transaction-pooler URI:"
NEXT_PUBLIC_SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
write_env NEXT_PUBLIC_APP_URL "http://localhost:3000"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
write_env DATABASE_URL "$DATABASE_URL"

stage "Database — apply the initial schema"
say "The migration creates 24 domain tables, RLS defaults, five storage buckets, and narrow realtime publication entries."
if confirm "Apply drizzle/0000_initial_relay_schema.sql to the new database?"; then
  export DATABASE_URL
  corepack pnpm db:migrate
else
  warn "Migration skipped. The application cannot persist data until it is applied."
  SKIPPED+=("initial database migration")
fi

stage "Vercel — create, configure, and deploy"
say "This creates a free Vercel project and configures production plus preview environments."
if [[ ! -f .vercel/project.json ]]; then
  vercel project add "$VERCEL_PROJECT_NAME" --scope "$VERCEL_SCOPE" >/dev/null 2>&1 || true
  vercel link --yes --project "$VERCEL_PROJECT_NAME" --scope "$VERCEL_SCOPE"
else
  say "This directory is already linked to a Vercel project."
fi
vercel project update "$VERCEL_PROJECT_NAME" --framework nextjs --auto-detect output-directory --auto-detect build-command --auto-detect install-command >/dev/null
PRODUCTION_URL="https://${VERCEL_PROJECT_NAME}.vercel.app"
set_vercel_env NEXT_PUBLIC_APP_URL "$PRODUCTION_URL"
set_vercel_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
set_vercel_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
set_vercel_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
set_vercel_env DATABASE_URL "$DATABASE_URL"
step "Deploying the production build."
vercel deploy --prod --yes
note "Stable production URL: $PRODUCTION_URL"

stage "Supabase Auth — email and redirect URLs"
say "Relay supports email/password and magic-link email. Supabase's default mailer is sufficient for initial testing."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/url-configuration"
step "Set Site URL to ${PRODUCTION_URL}."
step "Add redirect URL: http://localhost:3000/**"
step "Add redirect URL: ${PRODUCTION_URL}/**"
pause "Save the URL configuration, then press Enter."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Open Email and confirm Enable Email provider is on."
step "Keep Confirm email on. Password and magic-link flows can coexist."
pause "Save the Email provider settings, then press Enter."

stage "Google — OAuth client and Supabase provider"
say "Google needs one Web application OAuth client. The client secret stays in Google and Supabase; Relay does not store it locally."
open_url "https://console.cloud.google.com/auth/clients"
step "Create or select a Google Cloud project named Relay. Configure the OAuth consent screen for External users."
step "Create a Web application OAuth client named Relay Web."
step "Authorized JavaScript origins: http://localhost:3000"
step "Authorized JavaScript origins: ${PRODUCTION_URL}"
step "Authorized redirect URI: ${NEXT_PUBLIC_SUPABASE_URL}/auth/v1/callback"
step "Create the client and copy its Client ID and Client Secret."
pause "Keep the Google credentials copied, then press Enter."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Open Google, enable it, and paste the Client ID and Client Secret."
step "Save the Google provider."
pause "Finish the provider setup, then press Enter."

stage "Verification — local, database, and production"
export DATABASE_URL
step "Checking code quality and the production build."
corepack pnpm lint
corepack pnpm typecheck
corepack pnpm test
corepack pnpm build
step "Checking the deployed application."
if curl --fail --silent --show-error --head "$PRODUCTION_URL" >/dev/null; then
  say "Production responded successfully."
else
  warn "Production did not respond yet. Vercel may still be assigning the alias."
  SKIPPED+=("production URL response check")
fi
say "Use docs/integrations.md for the final email, Google, storage, and database smoke tests."

finish
